### ISSUE TITLE
OH SDO Agent Install Failed with ERROR: A value for HZN_AGBOT_URL must be specified

### ISSUE THREAD

**Issue by antonyjayaveeran** [open-horizon/SDO-support#110]
We are getting this issue ERROR: A value for HZN_AGBOT_URL must be specified with SDO onboarding process (https://github.com/open-horizon/SDO-support/blob/master/README-1.10.md)

SDO java client process trying to download the latest version of agent
./agent-install.sh -i https://github.com/open-horizon/anax/releases/latest/download -a <UUID> -o ORG_ID when onboarding begins.

Since there is an update to ANAX, included AGBOT_URL changes (https://github.com/open-horizon/anax/commit/693d41efa215ca21de0e0b357026d75f6f7d6515), but SDO java client did not change to the latest requirements. So, It is breaking the onboarding process from SDO.

1.	Is there a way we can pass Anax version as an env variable to the SDO client code? 
2.	where can we find the source code of this binary: https://github.com/open-horizon/SDO-support/releases/download/v1.10/sdo_device_binaries_1.10_linux_x64.tar.gz

**Comment by bmpotter** [comment]
@antonyjayaveeran I assume you were running this in the context of the [all-in-1](https://github.com/open-horizon/devops/blob/master/mgmt-hub/deploy-mgmt-hub.sh) environment ? I think i know why it is failing and i'm investigating a solution.

**Comment by antonyjayaveeran** [comment]
Hi @bmpotter, thanks for your reply.

I am running my own instances of SDO services. 

Right now, AGENT_INSTALL_URL Is being passed as an environment variable. I hope I have to use SDO_GET_PKGS_FROM Since AGENT_INSTALL_URL Is not used anymore. 
(https://github.com/open-horizon/SDO-support/commit/14bed3c23b7bf2049806751bea2a94f401561e35#diff-66bf7e5a5f3ac26ec7882a25e8942b73981e1caddcc6e84b096de67366a144fc)
Is that correct? 

Also, it would be great if you share the source code of this binary: https://github.com/open-horizon/SDO-support/releases/download/v1.10/sdo_device_binaries_1.10_linux_x64.tar.gz

**Comment by bmpotter** [comment]
@antonyjayaveeran Oh, ok. Yes, as a temporary work around you should be able to `export SDO_GET_PKGS_FROM=https://github.com/open-horizon/anax/releases/download/v2.29.0-415` when starting the `sdo-owner-services` container. (That's the last version of `agent-install.sh` before `HZN_AGBOT_URL` was added.)

I'm working on a general fix today, so in the future you won't have to set this env var.

**Comment by bmpotter** [comment]
Submitted PR https://github.com/open-horizon/anax/pull/2532 for `agent-install.sh` in the `anax` repo to fix this issue.

**Comment by bmpotter** [comment]
The general fix for this issue was implemented in https://github.com/open-horizon/SDO-support/issues/116 .

To answer the question above, the source comes from https://github.com/secure-device-onboard
