### ISSUE TITLE
SUSE Micro OS support for SDO

### ISSUE THREAD

**Issue by itskumaresan** [open-horizon/SDO-support#112]
Hello Team,

I was able to install the OH Agent manually in the SUSE Micro OS. 
However, when I try to set up the OH Agent on a SUSE Micro OS via SDO, as part of the SDO onboarding process, I could see the below error,

![suse-microos](https://user-images.githubusercontent.com/49601691/122923515-600e3b80-d397-11eb-8ece-9d5111a4ce58.png)

Please check.

Thank you.

**Comment by naphelps** [comment]
This is an Anax issue: [https://github.com/open-horizon/anax](https://github.com/open-horizon/anax)

SDO is depreciated. See [https://github.com/open-horizon/FDO-support](https://github.com/open-horizon/FDO-support)
