### ISSUE TITLE
SDO_RV_URL not accessible

### ISSUE THREAD

**Issue by gerwinbrill** [open-horizon/SDO-support#148]
The SDO_RV_URL=http://sdo-sbx.trustedservices.intel.com:80 is not accessible respectively resolvable in DNS at the moment!

**Comment by joewxboy** [comment]
@dlarson04 and @lorenzoking any ideas?

**Comment by naphelps** [comment]
SDO is depreciated. See [https://github.com/open-horizon/FDO-support](https://github.com/open-horizon/FDO-support)
