### ISSUE TITLE
Generate OCS-API swagger.json

### ISSUE THREAD

**Issue by t-fine** [open-horizon/SDO-support#27]
If there are good golang annotations for swagger, use that. Otherwise, create the file by hand (the OSC API is not that big, and probably won't be changing often).

Give the swagger.json file to joe pearson and rene to be published.

**Comment by lorenzoking** [comment]
Verified! Went through https://www-03preprod.ibm.com/support/knowledgecenter/SSFKVV_4.2/api/sdo_swagger.json
