### ISSUE TITLE
Update deploy-mgmt-hub.sh to add SDO owner service

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/SDO-support#28]
- [x] Add sdo-owner-service to `docker-compose.yml`
- [x] Test device DI and device boot (as documented in SDO-support readme)
- [x] Write a script to automate device DI and device boot
- [x] Update devops readme

Test by following https://github.com/open-horizon/devops/blob/master/mgmt-hub/README.md all the way thru the **Try Out SDO** section.

**Comment by bmpotter** [comment]
@lorenzoking please verify

**Comment by lorenzoking** [comment]
This has been verified through a test on a clean VM
