### ISSUE TITLE
Test the native client with Intel NUC

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/SDO-support#30]
- [x] Get native DI working in `simulate-mfg.sh`
- [x] Get native TO working in `owner-boot-device`
- [x] Install/enable `sdo_to.service` and use that to "boot" the device

**Comment by bmpotter** [comment]
@lorenzoking and @peeksake :  to test this, see me for the steps

**Comment by lorenzoking** [comment]
This has been verified through an end to end SDO integration test using the Intel Nuc
