### ISSUE TITLE
Test Intel's dev RV sandbox and production server

### ISSUE THREAD

**Issue by lorenzoking** [open-horizon/SDO-support#34]
From Intel:

You will need to get your owner public keys trusted by our RV server. The live public sandbox service (identical to the production service): http://sdo-sbx.trustedservices.intel.com . The live public service http://sdo.trustedservices.intel.com . Every customer that wants to use the Intel RVS needs to send us their public key.  There is a legal agreement that needs to be signed for this so if you think you’re ready to pursue  that option I’ll have Hussein look into the legal end.

**Comment by bmpotter** [comment]
I've verified that our code can be configured correctly to use Intel's sbx RV. The only remaining thing to do is fix https://github.com/open-horizon/SDO-support/issues/65 , so closing this issue.
