### ISSUE TITLE
Add labels, license content into docker image builds for Red Hat certification

### ISSUE THREAD

**Issue by cgiroua** [open-horizon/SDO-support#5]
Please see the following issue addressing the anax specific requirements:
open-horizon/anax#1686

A similar (SDO specific) set of labels will need to be generated on image build, as well as copying our LICENSE.txt into the same `/licenses` directory location.

**Comment by bmpotter** [comment]
Image openhorizon/sdo-owner-services:0.9.0 has the lables and license needed
