### ISSUE TITLE
SDO get horizon packages from CSS or anax/releases (instead of bluehorizon.network)

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/SDO-support#51]
- [x] Change SDO to have agent-install.sh get pkgs from anax repo or CSS instead of bluehorizon.network, and not install bluehorizon (this had to wait for the `agent-install.sh` completion, and the devops nightly builds)
- [x] Disable ocs-api config route (pen test identified a security exposure in this, and this route is not needed for production)
- [x] Add OCS API to pick up new version of agent-install.sh
- [x] Enable sdo-owner-services to accept non-encoded HZN_MGMT_HUB_CERT (requested by devops team)

**Comment by bmpotter** [comment]
@lorenzoking please verify

**Comment by lorenzoking** [comment]
Bruce's work has been verified
