### ISSUE TITLE
Support new SDO APIs in hzn command

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/SDO-support#61]
- [x] Change `hzn voucher import` to use `POST /api/vouchers` instead of `POST /api/voucher`, so we can deprecate the latter
- [ ] Add `hzn sdo version` to use `GET /api/version` to display the sdo version
- [ ] Add `hzn sdo rendezvous ping` to use `POST $SDO_RV_URL/mp/113/msg/20` to verify either the dev RV or Intel's sandbox or production RV (http://sdo-sbx.trustedservices.intel.com or http://sdo.trustedservices.intel.com)
- [ ] Add `hzn sdo verify` to verify the external OPS external host (dns or ip) and port (if Intel gives us a way), and anything else that can be verified
- [ ] Change the `hzn voucher import -h` info about the flags to be similar to [SDO PR 98](https://github.com/open-horizon/SDO-support/pull/99)
- [ ] Modify `hzn voucher import --pattern=<pattern-name>` to verify that the pattern exists in the exchange.
- [ ] Modify `hzn voucher import --policy=<node-policy-file>` to validate the schema of the node policy json file (just the json field names), if it doesn't already.
- [x] In ocs-api, change the voucher id not found to 404 http code, and change some of the 500's to 502 (and adjust swagger)
- [ ] Consider adding automatic swagger generation to ocs-api (optional)

**Comment by naphelps** [comment]
SDO is depreciated. See [https://github.com/open-horizon/FDO-support](https://github.com/open-horizon/FDO-support)
