### ISSUE TITLE
Several small SDO fixes

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/SDO-support#92]
- [x] Fix description of orgid query parameter in `ocs-api-swagger.json`
- [x] Remove logging of `FS_OWNER_KEYSTORE_PASSWORD` in `start-sdo-owner-services.sh`
- [x] Remove older device binary directories in simulate-mfg.sh
- [x] Change the default of SDO_DEVICE_USE_NATIVE_CLIENT to false
- [x] Make README.md a pointer to either README-1.8.md or README-1.10.md
- [x] Make HZN_ORG_ID optional
- [x] Move up to SDO 1.10.1

**Comment by TheMosquito** [comment]
Maybe include this stuff in this fix too:

**Comment by bmpotter** [comment]
@TheMosquito i included that in PR https://github.com/open-horizon/SDO-support/pull/95/files

**Comment by lorenzoking** [comment]
This issue has been fixed and tested and verified.
