### ISSUE TITLE
Support switching imported SDO voucher to different org

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/SDO-support#97]
Regarding changing the org of an imported voucher/device: i experimented with re-importing a voucher (to the same org or a different org):
- If the device hasn't been plugged in/booted yet, everything is fine. Importing it again overwrites the device's files in the OCS DB. Specifically: ocs/config/db/v1/devices/<device-uuid>/orgid.txt and ocs/config/db/v1/values/<device-uuid>_exec get the new org. So when the device is finally booted, it uses the new org.
- If the device has already been booted and SDO did its thing (install/registered the horizon agent), it updates file ocs/config/db/v1/devices/<device-uuid>/state.json with json like this: `{"to2State":"to2end","to2Timestamp":"2021-03-15T12:59:16.58596","to2Error":null,"to0Timestamp":"2021-03-12T16:10:57.644671","to0Error":null,"to0Ws":604800,"g3":null}`. Note "to2end". Once that happens, the intel sdo code in sdo-owner-services will never run to0 on it again to advertise it to the RV. So even if the device voucher is re-imported with a new org and the files above get updated with the new org, running `owner-boot-device` on the device again won't work because the RV no longer knows about the device

It is very late in the cycle, but i think we have a few choices for how to handle this case in 4.2.1:

1. Add a `DELETE /vouchers/{device-id}` API so they can delete a voucher and then re-import it. We probably need a delete API eventually anyway, just for completeness.
2. Add a `PATCH /vouchers/{device-id}` API that will just remove `to2end` from state.json. We probably need a this API eventually anyway too.
3. Modify `POST /vouchers` to remove `state.json` (if it exists) before creating the rest of the voucher-related files in the OCS DB. This code change is very localized, should be safe, and has no external changes.
4. Document as a Limitation that they can't change the org of an imported voucher whose device has already been booted.

We decided to go with solution #3 .

**Comment by lorenzoking** [comment]
Solution 3 has been tested and verified. 

- [x] Re-importing the voucher with a different org **before** the device has been booted. PASSED: The pre-created node in the previous org was deleted. 
- [x] Re-importing the voucher with a different org **after** the device has been booted. PASSED: the pre-created node in the previous org was deleted
